GET http://localhost:3003/user/005

###
POST http://localhost:3003/user
Content-Type:  application/json

{
	"name": "tete",
	"nickname": "tste",
	"email": "asro@ev.com"
}

###
PUT http://localhost:3003/user/001
Content-Type:  application/json

{
	"name": "Astro Dev",
	"nickname": "astrodev"
}

###
PUT http://localhost:3003/user/001
Content-Type:  application/json

{
	"name": "Astro Dev",
	"nickname": "astrodev"
}


